package com.jjundev.oneclickeng.feature.home.topic

import com.jjundev.oneclickeng.ui.foundation.OceIcon

/**
 * 홈 주제 선택 카탈로그(M3-08, FR-5). 주제를 로컬 상수로 번들해 핵심 콘텐츠(주제 선택)를 네트워크 로드에
 * 걸지 않는다. Firestore `config/topics` 원격 스왑은 v1.1 에 같은 seam 뒤로 이연한다.
 *
 * [promptSeed] 만 대화 생성기(LLM)에 전달된다 — [titleKo]/[emoji]/[group] 은 표시 전용. [beginnerFriendly]
 * 6개는 온보딩 첫 선택 후보와 정본을 공유한다(온보딩 상수를 이 카탈로그 파생으로 폐기).
 */
data class Topic(
    val id: String,
    val emoji: String,
    val titleKo: String,
    val group: TopicGroup,
    val beginnerFriendly: Boolean,
    val promptSeed: String,
    val icon: OceIcon = group.fallbackIcon,
)

/** 주제 4그룹(home §3.2). [labelKo] 는 세그먼트/섹션 라벨 표시값. */
enum class TopicGroup(
    val labelKo: String,
    val fallbackIcon: OceIcon,
) {
    Daily("일상·입문", OceIcon.LocalCafe),
    Travel("여행", OceIcon.Flight),
    Work("업무·커리어", OceIcon.BusinessCenter),
    Life("생활·서비스", OceIcon.AccountBalance),
}

@Suppress("LargeClass") // The fixed 120-row bundled catalog intentionally owns its complete inventory.
object TopicCatalog {
    /** 120개(id, emoji, titleKo, group, beginnerFriendly, promptSeed). */
    val ALL: List<Topic> =
        listOf(
            Topic(
                id = "cafe-order",
                emoji = "☕",
                titleKo = "카페에서 주문하기",
                group = TopicGroup.Daily,
                beginnerFriendly = true,
                promptSeed = "ordering a drink and a snack at a café counter",
                icon = OceIcon.LocalCafe,
            ),
            Topic(
                id = "weather-smalltalk",
                emoji = "🌤️",
                titleKo = "날씨로 스몰토크",
                group = TopicGroup.Daily,
                beginnerFriendly = true,
                promptSeed = "making light small talk about today's weather with an acquaintance",
                icon = OceIcon.PartlyCloudyDay,
            ),
            Topic(
                id = "hobby-intro",
                emoji = "🎸",
                titleKo = "취미·자기소개",
                group = TopicGroup.Daily,
                beginnerFriendly = true,
                promptSeed = "introducing yourself and talking about your hobbies to someone new",
                icon = OceIcon.Interests,
            ),
            Topic(
                id = "restaurant",
                emoji = "🍽️",
                titleKo = "레스토랑 주문·예약",
                group = TopicGroup.Daily,
                beginnerFriendly = true,
                promptSeed = "ordering food or booking a table at a restaurant",
                icon = OceIcon.Restaurant,
            ),
            Topic(
                id = "refund-exchange",
                emoji = "🛒",
                titleKo = "환불·교환 요청",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a store clerk for a refund or exchange on a purchased item",
                icon = OceIcon.ShoppingCart,
            ),
            Topic(
                id = "airport-immigration",
                emoji = "✈️",
                titleKo = "공항 입국 심사",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "answering an officer's questions at airport immigration",
                icon = OceIcon.Flight,
            ),
            Topic(
                id = "hotel-checkin",
                emoji = "🏨",
                titleKo = "호텔 체크인",
                group = TopicGroup.Travel,
                beginnerFriendly = true,
                promptSeed = "checking in at a hotel front desk",
                icon = OceIcon.Hotel,
            ),
            Topic(
                id = "taxi",
                emoji = "🚕",
                titleKo = "택시 목적지 말하기",
                group = TopicGroup.Travel,
                beginnerFriendly = true,
                promptSeed = "telling a taxi driver your destination and giving directions",
                icon = OceIcon.LocalTaxi,
            ),
            Topic(
                id = "asking-directions",
                emoji = "🧭",
                titleKo = "길 묻기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking a stranger on the street how to get to a place",
                icon = OceIcon.Directions,
            ),
            Topic(
                id = "company-intro",
                emoji = "🏢",
                titleKo = "회사에서 자기소개",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "introducing yourself to new colleagues on your first day at work",
                icon = OceIcon.BusinessCenter,
            ),
            Topic(
                id = "interview-intro",
                emoji = "💼",
                titleKo = "면접에서 자기소개",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "introducing yourself and answering opening questions in a job interview",
                icon = OceIcon.Work,
            ),
            Topic(
                id = "meeting-schedule",
                emoji = "📅",
                titleKo = "회의 일정 조율",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "coordinating a meeting time with a coworker",
                icon = OceIcon.Event,
            ),
            Topic(
                id = "hospital-symptoms",
                emoji = "🏥",
                titleKo = "병원에서 증상 설명",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "describing your symptoms to a doctor at a clinic",
                icon = OceIcon.LocalHospital,
            ),
            Topic(
                id = "pharmacy",
                emoji = "💊",
                titleKo = "약국에서 약 사기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "buying over-the-counter medicine and asking the pharmacist for advice",
                icon = OceIcon.Medication,
            ),
            Topic(
                id = "bank-account",
                emoji = "🏦",
                titleKo = "은행 계좌 개설",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "opening a new bank account at a branch",
                icon = OceIcon.AccountBalance,
            ),
            Topic(
                id = "phone-booking",
                emoji = "📞",
                titleKo = "전화로 예약하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "making a reservation over the phone",
                icon = OceIcon.Call,
            ),
            Topic(
                id = "greeting-neighbor",
                emoji = "👋",
                titleKo = "이웃에게 인사하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "greeting a new neighbor and making a friendly introduction",
            ),
            Topic(
                id = "introduce-family",
                emoji = "👨‍👩‍👧",
                titleKo = "가족 소개하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "introducing your family during a casual conversation",
            ),
            Topic(
                id = "weekend-plans",
                emoji = "🗓️",
                titleKo = "주말 계획 묻기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a friend about their weekend plans",
            ),
            Topic(
                id = "invite-friend",
                emoji = "🎉",
                titleKo = "친구 초대하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "inviting a friend to join a casual activity",
            ),
            Topic(
                id = "cancel-plans",
                emoji = "🙏",
                titleKo = "약속 취소하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "politely cancelling plans and suggesting another time",
            ),
            Topic(
                id = "birthday-wishes",
                emoji = "🎂",
                titleKo = "생일 축하하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "wishing someone a happy birthday and giving a small gift",
            ),
            Topic(
                id = "ask-favor",
                emoji = "🤝",
                titleKo = "부탁하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a friend for a small favor politely",
            ),
            Topic(
                id = "borrow-item",
                emoji = "📚",
                titleKo = "물건 빌리기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking to borrow an everyday item from a neighbor",
            ),
            Topic(
                id = "return-item",
                emoji = "🔁",
                titleKo = "빌린 물건 돌려주기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "returning a borrowed item and thanking its owner",
            ),
            Topic(
                id = "apartment-problem",
                emoji = "🏠",
                titleKo = "집 문제 알리기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "reporting a small problem in your apartment to the manager",
            ),
            Topic(
                id = "package-delivery",
                emoji = "📦",
                titleKo = "택배 받기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "talking to a courier about receiving a package",
            ),
            Topic(
                id = "laundry-room",
                emoji = "🧺",
                titleKo = "세탁실 이용하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking about using a shared laundry room",
            ),
            Topic(
                id = "grocery-shopping",
                emoji = "🛒",
                titleKo = "장보기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a grocery store worker where to find an item",
            ),
            Topic(
                id = "clothing-size",
                emoji = "👕",
                titleKo = "옷 사이즈 묻기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a shop assistant about clothing sizes",
            ),
            Topic(
                id = "salon-appointment",
                emoji = "💇",
                titleKo = "미용실 예약하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "booking a haircut and describing the style you want",
            ),
            Topic(
                id = "gym-membership",
                emoji = "🏋️",
                titleKo = "헬스장 등록하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking about gym membership plans and facilities",
            ),
            Topic(
                id = "library-card",
                emoji = "📖",
                titleKo = "도서관 카드 만들기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "applying for a library card and asking about borrowing rules",
            ),
            Topic(
                id = "pet-care",
                emoji = "🐶",
                titleKo = "반려동물 돌봄 부탁하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "arranging pet care with a friend while you are away",
            ),
            Topic(
                id = "cooking-recipe",
                emoji = "🍳",
                titleKo = "요리법 묻기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a friend how to cook a simple dish",
            ),
            Topic(
                id = "movie-plans",
                emoji = "🎬",
                titleKo = "영화 보러 가기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "choosing a movie and arranging a time to watch it",
            ),
            Topic(
                id = "concert-ticket",
                emoji = "🎵",
                titleKo = "공연 표 예매하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "buying tickets for a concert and choosing seats",
            ),
            Topic(
                id = "lost-and-found",
                emoji = "🔎",
                titleKo = "분실물 찾기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking at a lost-and-found desk about a missing item",
            ),
            Topic(
                id = "public-transport",
                emoji = "🚌",
                titleKo = "버스 이용하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking which bus to take and how to pay the fare",
            ),
            Topic(
                id = "school-parents",
                emoji = "🏫",
                titleKo = "학부모 상담하기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "speaking with a teacher about a child's school progress",
            ),
            Topic(
                id = "neighborhood-event",
                emoji = "🎪",
                titleKo = "동네 행사 묻기",
                group = TopicGroup.Daily,
                beginnerFriendly = false,
                promptSeed = "asking a neighbor about a local community event",
            ),
            Topic(
                id = "flight-checkin",
                emoji = "🛫",
                titleKo = "항공편 체크인",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "checking in for an international flight at the airport",
            ),
            Topic(
                id = "boarding-gate",
                emoji = "🚪",
                titleKo = "탑승구 찾기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking airport staff for directions to a boarding gate",
            ),
            Topic(
                id = "baggage-claim",
                emoji = "🧳",
                titleKo = "수하물 찾기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking for help when your luggage is missing at baggage claim",
            ),
            Topic(
                id = "customs-declaration",
                emoji = "🛃",
                titleKo = "세관 신고하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "answering customs questions about items you are carrying",
            ),
            Topic(
                id = "currency-exchange",
                emoji = "💱",
                titleKo = "환전하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "exchanging money at a currency exchange counter",
            ),
            Topic(
                id = "tourist-info",
                emoji = "ℹ️",
                titleKo = "관광 안내소 이용하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking a tourist information clerk for local recommendations",
            ),
            Topic(
                id = "museum-ticket",
                emoji = "🖼️",
                titleKo = "박물관 표 사기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "buying museum admission tickets and asking about exhibits",
            ),
            Topic(
                id = "train-ticket",
                emoji = "🚆",
                titleKo = "기차표 예매하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "buying a train ticket and choosing a departure time",
            ),
            Topic(
                id = "platform-change",
                emoji = "🚉",
                titleKo = "승강장 변경 확인하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "confirming a changed train platform with station staff",
            ),
            Topic(
                id = "car-rental",
                emoji = "🚗",
                titleKo = "렌터카 빌리기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "renting a car and reviewing the rental agreement",
            ),
            Topic(
                id = "gas-station",
                emoji = "⛽",
                titleKo = "주유소 이용하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking for fuel and payment options at a gas station",
            ),
            Topic(
                id = "beach-rental",
                emoji = "🏖️",
                titleKo = "해변 용품 빌리기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "renting beach equipment for the day",
            ),
            Topic(
                id = "tour-booking",
                emoji = "🗺️",
                titleKo = "투어 예약하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "booking a guided tour and asking what is included",
            ),
            Topic(
                id = "lost-passport",
                emoji = "🛂",
                titleKo = "여권 분실 신고하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "reporting a lost passport and asking for emergency help",
            ),
            Topic(
                id = "emergency-help",
                emoji = "🚨",
                titleKo = "여행 중 긴급 도움 요청",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking for urgent help while traveling in an unfamiliar city",
            ),
            Topic(
                id = "hotel-room-issue",
                emoji = "🛏️",
                titleKo = "호텔 객실 문제 알리기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "reporting a problem with your hotel room to the front desk",
            ),
            Topic(
                id = "hotel-breakfast",
                emoji = "🥐",
                titleKo = "호텔 조식 문의하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking about breakfast hours and dietary options at a hotel",
            ),
            Topic(
                id = "late-checkout",
                emoji = "⏰",
                titleKo = "레이트 체크아웃 요청",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "requesting a late checkout at a hotel politely",
            ),
            Topic(
                id = "wifi-password",
                emoji = "📶",
                titleKo = "와이파이 비밀번호 묻기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking for the Wi-Fi password at a hotel or café",
            ),
            Topic(
                id = "travel-restaurant",
                emoji = "🍜",
                titleKo = "여행지 식당 추천받기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking a local for a restaurant recommendation while traveling",
            ),
            Topic(
                id = "local-market",
                emoji = "🧺",
                titleKo = "현지 시장에서 쇼핑하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "buying food at a local market and asking about prices",
            ),
            Topic(
                id = "souvenir-shopping",
                emoji = "🎁",
                titleKo = "기념품 사기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "choosing souvenirs and asking a shopkeeper for suggestions",
            ),
            Topic(
                id = "travel-photo",
                emoji = "📸",
                titleKo = "사진 촬영 부탁하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking another traveler to take a photo for you",
            ),
            Topic(
                id = "train-delay",
                emoji = "⌛",
                titleKo = "기차 지연 문의하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "asking station staff about a delayed train",
            ),
            Topic(
                id = "ride-share",
                emoji = "🚙",
                titleKo = "차량 호출하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "arranging a ride-share pickup and confirming the destination",
            ),
            Topic(
                id = "border-crossing",
                emoji = "🗺️",
                titleKo = "국경 통과하기",
                group = TopicGroup.Travel,
                beginnerFriendly = false,
                promptSeed = "answering questions while crossing a land border",
            ),
            Topic(
                id = "email-followup",
                emoji = "✉️",
                titleKo = "이메일 후속 연락하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "following up on an unanswered work email politely",
            ),
            Topic(
                id = "project-update",
                emoji = "📊",
                titleKo = "프로젝트 진행 상황 공유",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "giving a concise update on your project progress",
            ),
            Topic(
                id = "task-prioritization",
                emoji = "✅",
                titleKo = "업무 우선순위 정하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "discussing which tasks should be prioritized this week",
            ),
            Topic(
                id = "deadline-extension",
                emoji = "⏳",
                titleKo = "마감 연장 요청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "requesting more time to complete a work task",
            ),
            Topic(
                id = "request-feedback",
                emoji = "💬",
                titleKo = "피드백 요청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "asking a colleague for feedback on your work",
            ),
            Topic(
                id = "give-feedback",
                emoji = "🗣️",
                titleKo = "피드백 주기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "giving constructive feedback to a coworker",
            ),
            Topic(
                id = "ask-help",
                emoji = "🙋",
                titleKo = "업무 도움 요청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "asking a teammate for help with a difficult task",
            ),
            Topic(
                id = "delegate-task",
                emoji = "📌",
                titleKo = "업무 맡기기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "delegating a task and explaining the expected result",
            ),
            Topic(
                id = "meeting-agenda",
                emoji = "📝",
                titleKo = "회의 안건 정하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "proposing an agenda before a team meeting",
            ),
            Topic(
                id = "meeting-notes",
                emoji = "📒",
                titleKo = "회의록 공유하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "summarizing meeting decisions and next steps",
            ),
            Topic(
                id = "presentation-opening",
                emoji = "🎤",
                titleKo = "발표 시작하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "opening a work presentation and introducing the topic",
            ),
            Topic(
                id = "presentation-qna",
                emoji = "❓",
                titleKo = "발표 질의응답",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "answering a question after a business presentation",
            ),
            Topic(
                id = "client-call",
                emoji = "📞",
                titleKo = "고객과 통화하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "discussing a project update with a client on a call",
            ),
            Topic(
                id = "sales-demo",
                emoji = "🖥️",
                titleKo = "제품 시연하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "demonstrating a product feature to a potential customer",
            ),
            Topic(
                id = "negotiate-price",
                emoji = "🤝",
                titleKo = "가격 협상하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "negotiating a price and terms with a business partner",
            ),
            Topic(
                id = "invoice-question",
                emoji = "🧾",
                titleKo = "청구서 문의하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "asking about an invoice that has an unexpected charge",
            ),
            Topic(
                id = "office-equipment",
                emoji = "🖨️",
                titleKo = "사무용품 요청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "requesting office equipment or supplies from administration",
            ),
            Topic(
                id = "it-support",
                emoji = "💻",
                titleKo = "IT 지원 요청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "explaining a computer problem to IT support",
            ),
            Topic(
                id = "remote-work",
                emoji = "🏡",
                titleKo = "재택근무 조율하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "coordinating a remote-work schedule with your manager",
            ),
            Topic(
                id = "sick-leave",
                emoji = "🤒",
                titleKo = "병가 알리기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "informing your manager that you need sick leave",
            ),
            Topic(
                id = "vacation-request",
                emoji = "🌴",
                titleKo = "휴가 신청하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "requesting vacation days and arranging coverage",
            ),
            Topic(
                id = "performance-review",
                emoji = "⭐",
                titleKo = "성과 평가 면담",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "discussing goals and achievements in a performance review",
            ),
            Topic(
                id = "networking-event",
                emoji = "🥂",
                titleKo = "네트워킹 행사에서 대화하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "introducing yourself at a professional networking event",
            ),
            Topic(
                id = "recruiter-call",
                emoji = "📱",
                titleKo = "채용 담당자와 통화하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "speaking with a recruiter about a job opportunity",
            ),
            Topic(
                id = "onboarding-question",
                emoji = "🧭",
                titleKo = "입사 초기 질문하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "asking a coworker about a new employee process",
            ),
            Topic(
                id = "schedule-interview",
                emoji = "📅",
                titleKo = "면접 일정 잡기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "arranging an interview time with a candidate",
            ),
            Topic(
                id = "workplace-conflict",
                emoji = "⚖️",
                titleKo = "직장 갈등 대화하기",
                group = TopicGroup.Work,
                beginnerFriendly = false,
                promptSeed = "calmly discussing a workplace disagreement with a colleague",
            ),
            Topic(
                id = "emergency-call",
                emoji = "📞",
                titleKo = "긴급 전화하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "calling emergency services and describing an urgent situation",
            ),
            Topic(
                id = "dentist-appointment",
                emoji = "🦷",
                titleKo = "치과 예약하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "booking a dental appointment and describing a tooth problem",
            ),
            Topic(
                id = "vision-exam",
                emoji = "👓",
                titleKo = "시력 검사 받기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "arranging an eye exam and asking about new glasses",
            ),
            Topic(
                id = "health-insurance",
                emoji = "🩺",
                titleKo = "건강보험 문의하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking an insurance representative about health coverage",
            ),
            Topic(
                id = "prescription-refill",
                emoji = "💊",
                titleKo = "처방약 재조제 요청",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "requesting a refill for a prescription medicine",
            ),
            Topic(
                id = "bank-transfer",
                emoji = "💸",
                titleKo = "은행 송금하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking how to make a bank transfer at a branch",
            ),
            Topic(
                id = "credit-card-lost",
                emoji = "💳",
                titleKo = "신용카드 분실 신고",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "reporting a lost credit card and asking for a replacement",
            ),
            Topic(
                id = "bill-payment",
                emoji = "🧾",
                titleKo = "공과금 납부하기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "paying a utility bill and asking about the due date",
            ),
            Topic(
                id = "post-office",
                emoji = "📮",
                titleKo = "우체국에서 소포 보내기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "sending a package at the post office and choosing delivery options",
            ),
            Topic(
                id = "internet-installation",
                emoji = "🌐",
                titleKo = "인터넷 설치 예약",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "scheduling a home internet installation appointment",
            ),
            Topic(
                id = "mobile-plan",
                emoji = "📱",
                titleKo = "휴대폰 요금제 변경",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "comparing mobile phone plans at a service store",
            ),
            Topic(
                id = "utility-outage",
                emoji = "💡",
                titleKo = "정전·단수 신고",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "reporting a power or water outage to the utility company",
            ),
            Topic(
                id = "landlord-repair",
                emoji = "🔧",
                titleKo = "집 수리 요청",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking a landlord to arrange a repair in your home",
            ),
            Topic(
                id = "police-report",
                emoji = "👮",
                titleKo = "경찰 신고 접수",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "filing a police report about a non-emergency incident",
            ),
            Topic(
                id = "legal-consultation",
                emoji = "⚖️",
                titleKo = "법률 상담 예약",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "booking an initial consultation with a lawyer",
            ),
            Topic(
                id = "child-school",
                emoji = "🎒",
                titleKo = "자녀 학교 문의",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking a school office about enrollment requirements",
            ),
            Topic(
                id = "daycare-pickup",
                emoji = "🧸",
                titleKo = "어린이집 하원 조율",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "coordinating a daycare pickup with a caregiver",
            ),
            Topic(
                id = "car-repair",
                emoji = "🔧",
                titleKo = "자동차 수리 맡기기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "describing a car problem at an auto repair shop",
            ),
            Topic(
                id = "car-insurance",
                emoji = "🚘",
                titleKo = "자동차 보험 문의",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking about car insurance coverage and pricing",
            ),
            Topic(
                id = "parking-ticket",
                emoji = "🅿️",
                titleKo = "주차 위반 딱지 문의",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking how to pay or appeal a parking ticket",
            ),
            Topic(
                id = "recycling-rules",
                emoji = "♻️",
                titleKo = "재활용 규칙 묻기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking a neighbor about local recycling rules",
            ),
            Topic(
                id = "community-class",
                emoji = "🧑‍🎨",
                titleKo = "지역 강좌 신청",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "registering for a community class and asking about materials",
            ),
            Topic(
                id = "volunteer-signup",
                emoji = "🙌",
                titleKo = "봉사활동 신청",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "signing up to volunteer for a local organization",
            ),
            Topic(
                id = "voting-info",
                emoji = "🗳️",
                titleKo = "투표 정보 묻기",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking where and when to vote in a local election",
            ),
            Topic(
                id = "donation-center",
                emoji = "❤️",
                titleKo = "기부 센터 이용",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "asking a donation center what items they accept",
            ),
            Topic(
                id = "fitness-class",
                emoji = "🧘",
                titleKo = "운동 수업 등록",
                group = TopicGroup.Life,
                beginnerFriendly = false,
                promptSeed = "registering for a fitness class and asking about its schedule",
            ),
        )

    /** 온보딩 첫 선택 후보(beginnerFriendly 6개, seed order). */
    val beginnerFriendly: List<Topic> = ALL.filter { it.beginnerFriendly }

    /** 한 그룹의 주제. */
    fun inGroup(group: TopicGroup): List<Topic> = ALL.filter { it.group == group }

    /**
     * 추천 [count]개(기본 6) — 날짜/새로고침 기반 **결정적 순환**(home §3.4, 랜덤/서버 config 미사용).
     * 120 은 6 의 배수이지만 순환 모듈로로 창을 감아 항상 [count]개를 채운다.
     * @param dayIndex 오늘의 정수 키(예: KST epochDay). 같은 날은 같은 창.
     * @param refresh 새로고침 횟수 — 창을 [count]칸씩 결정적으로 전진시킨다.
     */
    fun recommended(
        dayIndex: Long,
        refresh: Int = 0,
        count: Int = DEFAULT_RECOMMENDED,
    ): List<Topic> {
        val base = (dayIndex + refresh) * count
        return (0 until count).map { ALL[((base + it).mod(ALL.size.toLong())).toInt()] }
    }

    const val DEFAULT_RECOMMENDED = 6
}
